# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-01 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='q1',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='q10',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='q2',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='q3',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='q4',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='q5',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='q6',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='q7',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='q8',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='q9',
            old_name='name',
            new_name='description',
        ),
    ]
