# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-01 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161201_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Q1')),
                ('Q10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Q10')),
                ('Q2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Q2')),
                ('Q3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Q3')),
                ('Q4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Q4')),
                ('Q5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Q5')),
                ('Q6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Q6')),
                ('Q7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Q7')),
                ('Q8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Q8')),
                ('Q9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Q9')),
            ],
            options={
                'db_table': 'survey',
            },
        ),
    ]
