# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-01 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='cntry',
            field=models.CharField(default='PT', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='dweight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='idno',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='pspwght',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='pweight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
