# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-02 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161201_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q1',
            name='description',
            field=models.CharField(help_text=b'Question description 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='q10',
            name='description',
            field=models.CharField(help_text=b'Question description 10', max_length=100),
        ),
        migrations.AlterField(
            model_name='q2',
            name='description',
            field=models.CharField(help_text=b'Question description 2', max_length=100),
        ),
        migrations.AlterField(
            model_name='q3',
            name='description',
            field=models.CharField(help_text=b'Question description 3', max_length=100),
        ),
        migrations.AlterField(
            model_name='q4',
            name='description',
            field=models.CharField(help_text=b'Question description 4', max_length=100),
        ),
        migrations.AlterField(
            model_name='q5',
            name='description',
            field=models.CharField(help_text=b'Question description 5', max_length=100),
        ),
        migrations.AlterField(
            model_name='q6',
            name='description',
            field=models.CharField(help_text=b'Question description 6', max_length=100),
        ),
        migrations.AlterField(
            model_name='q7',
            name='description',
            field=models.CharField(help_text=b'Question description 7', max_length=100),
        ),
        migrations.AlterField(
            model_name='q8',
            name='description',
            field=models.CharField(help_text=b'Question description 8', max_length=100),
        ),
        migrations.AlterField(
            model_name='q9',
            name='description',
            field=models.CharField(help_text=b'Question description 9', max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='Q1',
            field=models.ForeignKey(help_text=b'Q1', on_delete=django.db.models.deletion.CASCADE, to='core.Q1'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='Q10',
            field=models.ForeignKey(help_text=b'Q10', on_delete=django.db.models.deletion.CASCADE, to='core.Q10'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='Q2',
            field=models.ForeignKey(help_text=b'Q2', on_delete=django.db.models.deletion.CASCADE, to='core.Q2'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='Q3',
            field=models.ForeignKey(help_text=b'Q3', on_delete=django.db.models.deletion.CASCADE, to='core.Q3'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='Q4',
            field=models.ForeignKey(help_text=b'Q4', on_delete=django.db.models.deletion.CASCADE, to='core.Q4'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='Q5',
            field=models.ForeignKey(help_text=b'Q5', on_delete=django.db.models.deletion.CASCADE, to='core.Q5'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='Q6',
            field=models.ForeignKey(help_text=b'Q6', on_delete=django.db.models.deletion.CASCADE, to='core.Q6'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='Q7',
            field=models.ForeignKey(help_text=b'Q7', on_delete=django.db.models.deletion.CASCADE, to='core.Q7'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='Q8',
            field=models.ForeignKey(help_text=b'Q8', on_delete=django.db.models.deletion.CASCADE, to='core.Q8'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='Q9',
            field=models.ForeignKey(help_text=b'Q9', on_delete=django.db.models.deletion.CASCADE, to='core.Q9'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='cntry',
            field=models.CharField(help_text=b'Interviewee residence country', max_length=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='dweight',
            field=models.FloatField(help_text=b'Weight'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='idno',
            field=models.IntegerField(help_text=b'Interviewee identification', unique=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(help_text=b'ESS Edition and Year', max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='pspwght',
            field=models.FloatField(help_text=b'Weight'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='pweight',
            field=models.FloatField(help_text=b'Weight'),
        ),
    ]
